global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'self'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ai_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api.local:8008']
  - job_name: 'qdrant'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:6333']
